Java = int(input("Enter Java Marks:"))
Python = int(input("Enter Python Marks:"))
Database = int(input("Enter Database Marks:"))
WebDevelopemt = int(input("Enter WebDevelopement Marks:"))
Dotnet = int(input("Enter Dotnet Marks:"))
print()
print("My java marks is:", Java)
print("My python marks is:", Python)
print("My database marks is:", Database)
print("My webdevelopement marks is:", WebDevelopemt)
print("My java dotnet is:", Dotnet)